### ISSUE TITLE
[design] Use Mozilla building blocks for headers

### ISSUE THREAD

**Issue by eliemichel** [Phyks/VelibFxos#13]
See [Header Building Block on MDN](https://developer.mozilla.org/en-US/Apps/Design/Firefox_OS_building_blocks/Header).
It may also avoid the overflow that append when the tab is empty.

**Comment by Phyks** [comment]
:+1:, especially for the overflow (unnecessary scroll).

**Comment by indydedeken** [comment]
Fixed, but : 
- it doesn't stay fixed on the top of the screen,
- "back" icon is a png and it's really ugly.

**Comment by Phyks** [comment]
:+1: for the ugly png…

**Comment by indydedeken** [comment]
@eliemichel Any reason to keep this issue alive ?

**Comment by eliemichel** [comment]
Well I am still not convinced by graphical glitches I can notice, but it may not be completely related so I will open a new issue.

**Comment by eliemichel** [comment]
Done in #41
